version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: kagurazakanyaa/qbittorrentee:latest
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUIPORT=8180
    volumes:
      - ./config:/config
      - ./downloads:/downloads
